# Generated by Django 5.0.3 on 2024-03-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
